import type { NextPage } from 'next';
import { useEffect } from 'react';

export interface IPage {
  setTitle: any;
}

const About: NextPage<IPage> = (props) => {
  useEffect(() => {
    props.setTitle('About');
  }, [props]);
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <h2>About Page</h2>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, cum
        officiis dolores quibusdam saepe iusto qui reiciendis alias explicabo
        labore ut id. Nisi unde impedit autem eligendi inventore quis ipsum?
      </p>
    </div>
  );
};

export default About;
