import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';

export interface IPage {
  setTitle: any;
}

const Contact: NextPage<IPage> = (props) => {
  useEffect(() => {
    props.setTitle('Contact');
  }, [props]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Contact Page</h2>
    </div>
  );
};

export default Contact;
